[project]
name = "mcp-openai-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.8.1",
    "openai>=1.90.0",
    "pydantic>=2.11.7",
    "python-dotenv>=1.1.0",
]
